kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/glynnbailey/checky


steps:

- name: test-api
  image: golang
  pull: always
  commands:
  - cd api
  - go get -v
  - go build -v
  - go test -v

- name: test-checker
  image: golang
  pull: always
  commands:
  - cd checker
  - go get -v
  - go build -v
  - go test -v

- name: test-web
  image: golang
  pull: always
  commands:
  - cd web
  - go get -v
  - go build -v
  - go test -v

- name: publish-api
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_HUB_USERNAME
    password:
      from_secret: DOCKER_HUB_PASSWORD
    repo: glynnbailey/checky-api
    tags: latest
    context: /go/src/github.com/glynnbailey/checky/api/.
    dockerfile: /go/src/github.com/glynnbailey/checky/api/Dockerfile

- name: publish-checker
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_HUB_USERNAME
    password:
      from_secret: DOCKER_HUB_PASSWORD
    repo: glynnbailey/checky-checker
    tags: latest
    context: /go/src/github.com/glynnbailey/checky/checker/.
    dockerfile: /go/src/github.com/glynnbailey/checky/checker/Dockerfile

- name: publish-web
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_HUB_USERNAME
    password:
      from_secret: DOCKER_HUB_PASSWORD
    repo: glynnbailey/checky-web
    tags: latest
    context: /go/src/github.com/glynnbailey/checky/web/.
    dockerfile: /go/src/github.com/glynnbailey/checky/web/Dockerfile

