kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/glynnbailey/checky

steps:
- name: go-api
  image: golang
  pull: always
  commands:
  - cd api
  - go get
  - go build
  - go test

- name: go-checker
  image: golang
  pull: always
  commands:
  - cd checker
  - go get
  - go build
  - go test

- name: go-web
  image: golang
  pull: always
  commands:
  - cd web
  - go get
  - go build
  - go test
