kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/glynnbailey/checky

steps:
- name: go-api
  image: golang
  pull: always
  commands:
  - cd api
  - go get -v
  - go build -v
  - go test -v

- name: go-checker
  image: golang
  pull: always
  commands:
  - cd checker
  - go get -v
  - go build -v
  - go test -v

- name: go-web
  image: golang
  pull: always
  commands:
  - cd web
  - go get -v
  - go build -v
  - go test -v

- name: publish-api
  image: plugins/docker
  detach: true
  settings:
    username:
      from_secret: DOCKER_HUB_USERNAME
    password:
      from_secret: DOCKER_HUB_PASSWORD
    repo: glynnbailey/checky-api
    tags: latest
    dockerfile: api/Dockerfile

- name: publish-checker
  image: plugins/docker
  detach: true
  settings:
    username:
      from_secret: DOCKER_HUB_USERNAME
    password:
      from_secret: DOCKER_HUB_PASSWORD
    repo: glynnbailey/checky-checker
    tags: latest
    dockerfile: checker/Dockerfile

- name: publish-web
  image: plugins/docker
  detach: true
  settings:
    username:
      from_secret: DOCKER_HUB_USERNAME
    password:
      from_secret: DOCKER_HUB_PASSWORD
    repo: glynnbailey/checky-web
    tags: latest
    dockerfile: web/Dockerfile
