version: '3.7'

networks:
  postgres:
    external: true

services:
  checker:
    build: ./checker/
    restart: always
    networks:
      - postgres

  api:
    build: ./api/
    restart: always
    ports:
      - "81:80"
    networks:
      - postgres

#  web:
#    build: ./web/
#    restart: always
#    ports:
#      - "80:80"
#    depends_on:
#      - checker
