version: '3.7'

networks:
  checky:
  postgres:
    external: true

services:
  api:
    build: ./api/
    image: glynnbailey/checky-api
    restart: always
    networks:
      - checky
      - postgres
#    ports:
#      - "81:80"
    environment:
      - POSTGRES_CONNECTION=postgres://checky:checky@postgres/checky?sslmode=disable


  checker:
    build: ./checker/
    image: glynnbailey/checky-checker
    restart: always
    depends_on:
      - api
    networks:
      - checky

  web:
    build: ./web/
    image: glynnbailey/checky-web
    restart: always
    networks:
      - checky
    ports:
      - "80:80"
    depends_on:
      - api
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:traefik.dataslave.net"
