version: '3.7'

networks:
  checky:
  postgres:
    external: true

services:
  api:
    build: ./api/
    restart: always
    networks:
      - checky
      - postgres
    ports:
      - "81:80"

  checker:
    build: ./checker/
    restart: always
    depends_on:
      - api
    networks:
      - checky

  web:
    build: ./web/
    restart: always
    networks:
      - checky
    ports:
      - "80:80"
    depends_on:
      - api

# TODO postgres container
